load("@rules_python//python:pip.bzl", "compile_pip_requirements")

compile_pip_requirements(
    name = "docs",
    src = "docs.txt",
    # requirements_lock = "docs.lock.txt",
    requirements_txt = "docs.lock.txt",
)
